# This compose file is for https://coolify.io/ Context is set to "." becuase coolify effectively copies the compose file to root and runs it from there
# It expects you to run pg database separately with replication set to logical https://zero.rocicorp.dev/docs/connecting-to-postgres
# You will need to set domains for both containers. Then you will need to pass those domain to ENV variables and set VITE_ZERO_DOMAIN env as Build Variable.
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #     args:
  #       - VITE_ZERO_DOMAIN=${VITE_ZERO_DOMAIN} # Domain for zero container
  #   environment:
  #     - NITRO_PORT=80
  #     - NODE_ENV=production
  #     - DATABASE_URL=${DATABASE_URL}
  #     - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
  #     - BETTER_AUTH_URL=${BETTER_AUTH_URL} # Domain for web container
  #     - MIGRATE=true
  zerosync:
    build:
      context: .
      dockerfile: ./docker/zero.Dockerfile
    environment:
      - ZERO_UPSTREAM_DB=${ZERO_UPSTREAM_DB}
      - ZERO_CVR_DB=${ZERO_CVR_DB}
      - ZERO_CHANGE_DB=${ZERO_CHANGE_DB}
      - ZERO_AUTH_JWKS_URL=${ZERO_AUTH_JWKS_URL} # Domain for web container + /api/auth/jwks
      - ZERO_REPLICA_FILE=/zero_data/zstart_replica.db
      - ZERO_PORT=80
    volumes:
      - zero_replica:/zero_data

volumes:
  zero_replica:
